org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.235
neo_version_range=[21.1.0,)
loader_version_range=[4,)

pneumaticcraft_version=8.2.20+mc1.21.1
pneumaticcraft_version_range=[8.2.0,)

mekanism_version=1.21.1-10.7.16.82
mekanism_version_range=[10.7.0,)

enderio_version=8.2.11-beta
enderio_version_range=[8.2.0,)

maries_lib_version=0.1.1-beta.4
maries_framework_version_range=[0.1.1-beta.4,)

mod_id=thermalsystems
mod_name=Thermal Systems
mod_license=All Rights Reserved
mod_version=0.0.1-beta
mod_group_id=com.marie.thermalsystems
mod_authors=Marie
mod_description=A working climate simulation core.
